definitions:
  internal.InternalGenerateReq:
    properties:
      data:
        description: format yyyy-mm-dd
        type: string
      uid:
        type: integer
    type: object
  internal.InternalUsualMsgPostReq:
    properties:
      app_name:
        type: string
      duration:
        type: integer
    type: object
  route.UserLoginReq:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  route.UserLogupReq:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: Lvshujun0918@163.com
    name: 吕舒君
  description: 提供所有API接口的说明文档
  title: 知时后端API文档
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 检查Gin和数据库服务的状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 获取服务状态
      tags:
      - Status
  /user/info/{u_id}:
    get:
      consumes:
      - application/json
      description: 获取指定用户的信息
      parameters:
      - description: 用户ID
        in: path
        name: u_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 获取用户信息
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录获取JWT token
      parameters:
      - description: 用户登录信息
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/route.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - User
  /user/logup:
    post:
      consumes:
      - application/json
      description: 新用户注册
      parameters:
      - description: 用户注册信息
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/route.UserLogupReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - User
  /v1/msg/post:
    post:
      consumes:
      - application/json
      description: 提交一条消息记录
      parameters:
      - description: 用户ID
        in: query
        name: u_id
        required: true
        type: integer
      - description: 消息内容
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/internal.InternalUsualMsgPostReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 发布消息
      tags:
      - Message
  /v1/report/{date}:
    get:
      consumes:
      - application/json
      description: 根据日期生成报告
      parameters:
      - description: 请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal.InternalGenerateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 生成报告
      tags:
      - Report
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
